/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.ImageIcon;

/**
 *
 * @author couto
 */
public class ViewSelectedPaciente extends javax.swing.JFrame {

    /**
     * Creates new form a
     */
    public ViewSelectedPaciente() {
        initComponents();
        /*Icon Janela*/
        setIconImage(new ImageIcon(getClass().getResource("/images/icon.png")).getImage());
        /*Background*/
        sVGImage1.setSvgImage("images/BackgroundCadastroPaciente.svg", 1000, 640);
        sVGImage2.setSvgImage("images/returnIcon.svg", 24, 15);
        /*Permitindo a visibillidade da PlaceHolder nas Labels*/
        txtNomePaciente.setFocusable(true);
        txtEmailPaciente.setFocusable(true);
        txtEnderecoPaciente.setFocusable(true);
        txtIdade.setFocusable(true);
        txtCelular.setFocusable(true);
        txtCpf.setFocusable(true);
        txtProfissao.setFocusable(true);
        txtCausa.setFocusable(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNomePaciente = new javax.swing.JTextField();
        txtEmailPaciente = new javax.swing.JTextField();
        txtEnderecoPaciente = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtProfissao = new javax.swing.JTextField();
        txtCausa = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        btnCriarConta = new javax.swing.JButton();
        sVGImage2 = new view.SVGImage();
        sVGImage1 = new view.SVGImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Paciente");
        setLocation(new java.awt.Point(250, 50));
        setMinimumSize(new java.awt.Dimension(1000, 640));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNomePaciente.setBackground(new java.awt.Color(247, 247, 247));
        txtNomePaciente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNomePaciente.setText("Nome");
        txtNomePaciente.setToolTipText("");
        txtNomePaciente.setBorder(null);
        txtNomePaciente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomePacienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomePacienteFocusLost(evt);
            }
        });
        jPanel1.add(txtNomePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 103, 230, 30));

        txtEmailPaciente.setBackground(new java.awt.Color(247, 247, 247));
        txtEmailPaciente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtEmailPaciente.setText("E-mail");
        txtEmailPaciente.setBorder(null);
        txtEmailPaciente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailPacienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailPacienteFocusLost(evt);
            }
        });
        jPanel1.add(txtEmailPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 148, 230, 30));

        txtEnderecoPaciente.setBackground(new java.awt.Color(247, 247, 247));
        txtEnderecoPaciente.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtEnderecoPaciente.setText("Endereço");
        txtEnderecoPaciente.setBorder(null);
        txtEnderecoPaciente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEnderecoPacienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEnderecoPacienteFocusLost(evt);
            }
        });
        jPanel1.add(txtEnderecoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 193, 230, 30));

        txtIdade.setBackground(new java.awt.Color(247, 247, 247));
        txtIdade.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtIdade.setText("Idade");
        txtIdade.setBorder(null);
        txtIdade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdadeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdadeFocusLost(evt);
            }
        });
        jPanel1.add(txtIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 238, 230, 30));

        txtCelular.setBackground(new java.awt.Color(247, 247, 247));
        txtCelular.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtCelular.setText("Celular");
        txtCelular.setBorder(null);
        txtCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCelularFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCelularFocusLost(evt);
            }
        });
        jPanel1.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 283, 230, 30));

        txtCpf.setBackground(new java.awt.Color(247, 247, 247));
        txtCpf.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtCpf.setText("CPF");
        txtCpf.setBorder(null);
        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpfFocusLost(evt);
            }
        });
        jPanel1.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 328, 230, 30));

        txtProfissao.setBackground(new java.awt.Color(247, 247, 247));
        txtProfissao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtProfissao.setText("Profissão");
        txtProfissao.setToolTipText("");
        txtProfissao.setBorder(null);
        txtProfissao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProfissaoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProfissaoFocusLost(evt);
            }
        });
        jPanel1.add(txtProfissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 373, 230, 30));

        txtCausa.setBackground(new java.awt.Color(247, 247, 247));
        txtCausa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtCausa.setText("Causa");
        txtCausa.setBorder(null);
        txtCausa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCausaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCausaFocusLost(evt);
            }
        });
        jPanel1.add(txtCausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 418, 230, 30));

        jPasswordField1.setBackground(new java.awt.Color(247, 247, 247));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 463, 230, 30));

        btnCriarConta.setBackground(new java.awt.Color(41, 151, 255));
        btnCriarConta.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnCriarConta.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarConta.setText("CRIAR CONTA");
        btnCriarConta.setBorder(null);
        jPanel1.add(btnCriarConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 505, 242, 35));

        sVGImage2.setText("sVGImage2");
        sVGImage2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sVGImage2MouseClicked(evt);
            }
        });
        jPanel1.add(sVGImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 24, 15));
        jPanel1.add(sVGImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*FocusGained*/
    private void txtNomePacienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomePacienteFocusGained
        if (txtNomePaciente.getText().equals("Nome")) {
            txtNomePaciente.setText("");
        }
    }//GEN-LAST:event_txtNomePacienteFocusGained

    private void txtEmailPacienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailPacienteFocusGained
        if (txtEmailPaciente.getText().equals("E-mail")) {
            txtEmailPaciente.setText("");
        }
    }//GEN-LAST:event_txtEmailPacienteFocusGained

    private void txtEnderecoPacienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEnderecoPacienteFocusGained
        if (txtEnderecoPaciente.getText().equals("Endereço")) {
            txtEnderecoPaciente.setText("");
        }
    }//GEN-LAST:event_txtEnderecoPacienteFocusGained

    private void txtIdadeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdadeFocusGained
        if (txtIdade.getText().equals("Idade")) {
            txtIdade.setText("");
        }
    }//GEN-LAST:event_txtIdadeFocusGained

    private void txtCelularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelularFocusGained
        if (txtCelular.getText().equals("Celular")) {
            txtCelular.setText("");
        }
    }//GEN-LAST:event_txtCelularFocusGained

    private void txtCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusGained
        if (txtCpf.getText().equals("CPF")) {
            txtCpf.setText("");
        }
    }//GEN-LAST:event_txtCpfFocusGained

    private void txtProfissaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProfissaoFocusGained
        if (txtProfissao.getText().equals("Profissão")) {
            txtProfissao.setText("");
        }
    }//GEN-LAST:event_txtProfissaoFocusGained

    private void txtCausaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCausaFocusGained
        if (txtCausa.getText().equals("Causa")) {
            txtCausa.setText("");
        }
    }//GEN-LAST:event_txtCausaFocusGained
    /*FocusLost*/
    private void txtNomePacienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomePacienteFocusLost
        if (txtNomePaciente.getText().equals("")) {
            txtNomePaciente.setText("Nome");
        }
    }//GEN-LAST:event_txtNomePacienteFocusLost

    private void txtEmailPacienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailPacienteFocusLost
        if (txtEmailPaciente.getText().equals("")) {
            txtEmailPaciente.setText("E-mail");
        }
    }//GEN-LAST:event_txtEmailPacienteFocusLost

    private void txtEnderecoPacienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEnderecoPacienteFocusLost
        if (txtEnderecoPaciente.getText().equals("")) {
            txtEnderecoPaciente.setText("Endereço");
        }
    }//GEN-LAST:event_txtEnderecoPacienteFocusLost

    private void txtIdadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdadeFocusLost
        if (txtIdade.getText().equals("")) {
            txtIdade.setText("Idade");
        }
    }//GEN-LAST:event_txtIdadeFocusLost

    private void txtCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelularFocusLost
        if (txtCelular.getText().equals("")) {
            txtCelular.setText("Celular");
        }
    }//GEN-LAST:event_txtCelularFocusLost

    private void txtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusLost
        if (txtCpf.getText().equals("")) {
            txtCpf.setText("CPF");
        }
    }//GEN-LAST:event_txtCpfFocusLost

    private void txtProfissaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProfissaoFocusLost
        if (txtProfissao.getText().equals("")) {
            txtProfissao.setText("Profissão");
        }
    }//GEN-LAST:event_txtProfissaoFocusLost

    private void txtCausaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCausaFocusLost
        if (txtCausa.getText().equals("")) {
            txtCausa.setText("Causa");
        }
    }//GEN-LAST:event_txtCausaFocusLost
    /*Click Voltar para tela selecionar tipo de Cadastro*/
    private void sVGImage2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sVGImage2MouseClicked
        ViewSelectTypeCadastro returnTypeCadastro = new ViewSelectTypeCadastro();
        this.setVisible(false);
        returnTypeCadastro.setVisible(true);
    }//GEN-LAST:event_sVGImage2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSelectedPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSelectedPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSelectedPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSelectedPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSelectedPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarConta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private view.SVGImage sVGImage1;
    private view.SVGImage sVGImage2;
    private javax.swing.JTextField txtCausa;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmailPaciente;
    private javax.swing.JTextField txtEnderecoPaciente;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtNomePaciente;
    private javax.swing.JTextField txtProfissao;
    // End of variables declaration//GEN-END:variables
}
