package view;

import dao.PacienteDao;
import javax.swing.*;
import model.Paciente;

public class ViewLogin extends javax.swing.JFrame {

    /**
     * Creates new form ViewLogin
     */
    public ViewLogin() {
        initComponents();
        /*Icon Janela*/
        // Define o ícone da janela como a imagem localizada em "/images/icon.png".
        setIconImage(new ImageIcon(getClass().getResource("/images/icon.png")).getImage());
        /*Background*/
        // Define a imagem de fundo SVG
        sVGImage1.setSvgImage("images/LoginLogoBackground.svg", 618, 640);
        // Define a imagem de fundo SVG
        sVGImage2.setSvgImage("images/LoginBoxBackground.svg", 382, 640);
        /*Permitindo a visibilidade da PlaceHolder nas Labels para quando clicar alterar para o texto digitado*/
        // Define o componente txtEmail como focável para permitir a edição do campo de texto.
        txtEmail.setFocusable(true);
        // Define a posição da janela como centralizada em relação à tela.
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        senhaPasswordField = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        lblRegistre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocation(new java.awt.Point(250, 50));
        setMaximumSize(new java.awt.Dimension(1000, 640));
        setMinimumSize(new java.awt.Dimension(1000, 640));
        setPreferredSize(new java.awt.Dimension(1000, 640));
        setResizable(false);

        jPanel2.setMaximumSize(new java.awt.Dimension(382, 640));
        jPanel2.setPreferredSize(new java.awt.Dimension(382, 640));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setBackground(new java.awt.Color(247, 247, 247));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtEmail.setText("Digite seu e-mail");
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 272, 230, 30));

        senhaPasswordField.setBackground(new java.awt.Color(247, 247, 247));
        senhaPasswordField.setBorder(null);
        senhaPasswordField.setPreferredSize(new java.awt.Dimension(76, 22));
        jPanel1.add(senhaPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 325, 230, 30));

        btnEntrar.setBackground(new java.awt.Color(227, 1, 64));
        btnEntrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("ENTRAR");
        btnEntrar.setBorder(null);
        btnEntrar.setBorderPainted(false);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 367, 245, 38));

        lblRegistre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRegistre.setForeground(new java.awt.Color(41, 151, 255));
        lblRegistre.setText("Registre-se");
        lblRegistre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistreMouseClicked(evt);
            }
        });
        jPanel1.add(lblRegistre, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 419, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(29, 29, 29));
        jLabel3.setText("Faça seu login");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(29, 29, 29));
        jLabel4.setText("na plataforma");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 211, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*Click Botão Registrar-se*/
    private void lblRegistreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistreMouseClicked
        // Cria uma instância da classe ViewSelectTypeCadastro
        ViewSelectTypeCadastro openSelectType = new ViewSelectTypeCadastro();
        // Torna a janela atual invisível
        this.setVisible(false);
        // Torna a janela openSelectType visível
        openSelectType.setVisible(true);
    }//GEN-LAST:event_lblRegistreMouseClicked
    /*FocusGained, Quando o componente é selecionado esse método é acionado.*/
    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // Verifica se o texto atual do campo de texto (txtEmail) é igual a "Digite seu e-mail".
        if (txtEmail.getText().equals("Digite seu e-mail")) {
            txtEmail.setText("");
        }
    }//GEN-LAST:event_txtEmailFocusGained
    /*FocusLost, Quando o componente perde o foco (deixa de ser selecionado).*/
    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // Verifica se o texto atual do campo de texto (txtEmail) está vazio.
        if (txtEmail.getText().equals("")) {
            txtEmail.setText("Digite seu e-mail");
            // Se estiver vazio, o texto é definido como "Digite seu e-mail".
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        //Aula dia 13 - Apostila 13_apostila... Pag3
        //Identificando Login  e Senha do digitada
        String email = txtEmail.getText();
        //Obtem a senha como char[] e converte em String
        String senha = new String(senhaPasswordField.getPassword());

        try {
            // Criando uma instância da classe Paciente com o email e senha
            Paciente paciente = new Paciente(email,senha);
            // Criando uma instância do PacienteDao para acessar métodos relacionados a pacientes
            PacienteDao pacientedao = new PacienteDao();
            if (pacientedao.existe(paciente)) {
                // Verifica se o paciente existe no banco de dados
                String nomePaciente = pacientedao.obterNomePaciente(email);
                // Exibe uma mensagem de boas-vindas com o nome do paciente
                JOptionPane.showMessageDialog(null, "Bem-Vindo "+nomePaciente+"!");
            } else {
                // Exibe uma mensagem de erro para um usuário inválido
                JOptionPane.showMessageDialog(null, "Usuário Inválido. Tente novamente.");
            }
        } catch (Exception e) {
            // Exibe uma mensagem de erro genérica caso ocorra uma exceção
            JOptionPane.showMessageDialog(null, "Problemas técnicos. Tente novamente mais tarde.");
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblRegistre;
    private javax.swing.JPasswordField senhaPasswordField;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables

}
