package view;

import javax.swing.*;
import model.bean.Funcionario;
import model.bean.Login;
import model.dao.FuncionarioDAO;
import model.dao.LoginDAO;
import view.Dashboard.Admin.DashboardAdmin;
import view.Dashboard.DashboardPrincipal;

public class ViewLogin extends javax.swing.JFrame {
    public static String emailLogin;
    
    public ViewLogin() {
        initComponents();
        /*Icon Janela*/
        // Define o ícone da janela como a imagem localizada em "/images/icon.png".
        setIconImage(new ImageIcon(getClass().getResource("/images/icon.png")).getImage());
        /*Background*/
        // Define a imagem de fundo SVG
        BackgroundRight.setSvgImage("images/BackgroundRight.svg", 618, 640);
        // Define a imagem de fundo SVG
        BackgroundLeft.setSvgImage("images/BackgroundLeft.svg", 382, 640);
        /*Permitindo a visibilidade da PlaceHolder nas Labels para quando clicar alterar para o texto digitado*/
        // Define o componente txtEmail como focável para permitir a edição do campo de texto.
        txtEmail.setFocusable(true);
        // Define a posição da janela como centralizada em relação à tela.
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        senhaPasswordField = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        lblRegistre = new javax.swing.JLabel();
        BackgroundLeft = new images.SVGImage();
        BackgroundRight = new images.SVGImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocation(new java.awt.Point(250, 50));
        setMaximumSize(new java.awt.Dimension(1000, 640));
        setMinimumSize(new java.awt.Dimension(1000, 640));
        setPreferredSize(new java.awt.Dimension(1000, 640));
        setResizable(false);

        jPanel2.setMaximumSize(new java.awt.Dimension(382, 640));
        jPanel2.setPreferredSize(new java.awt.Dimension(382, 640));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setBackground(new java.awt.Color(247, 247, 247));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtEmail.setText("Digite seu e-mail");
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 273, 230, 30));

        senhaPasswordField.setBackground(new java.awt.Color(247, 247, 247));
        senhaPasswordField.setBorder(null);
        senhaPasswordField.setPreferredSize(new java.awt.Dimension(76, 22));
        jPanel1.add(senhaPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 328, 230, 30));

        btnEntrar.setBackground(new java.awt.Color(227, 1, 64));
        btnEntrar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("ENTRAR");
        btnEntrar.setBorder(null);
        btnEntrar.setBorderPainted(false);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 372, 245, 38));

        lblRegistre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRegistre.setForeground(new java.awt.Color(41, 151, 255));
        lblRegistre.setText("Registre-se");
        lblRegistre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistreMouseClicked(evt);
            }
        });
        jPanel1.add(lblRegistre, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 423, -1, -1));

        BackgroundLeft.setText("sVGImage1");
        jPanel1.add(BackgroundLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 382, 640));

        BackgroundRight.setText("sVGImage1");
        jPanel1.add(BackgroundRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 618, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*Click Botão Registrar-se*/
    private void lblRegistreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistreMouseClicked
        // Cria uma instância da classe ViewSelectTypeCadastro
        ViewSelectTypeCadastro openSelectType = new ViewSelectTypeCadastro();
        // Torna a janela atual invisível
        this.setVisible(false);
        // Torna a janela openSelectType visível
        openSelectType.setVisible(true);
    }//GEN-LAST:event_lblRegistreMouseClicked
    /*FocusGained, Quando o componente é selecionado esse método é acionado.*/
    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // Verifica se o texto atual do campo de texto (txtEmail) é igual a "Digite seu e-mail".
        if (txtEmail.getText().equals("Digite seu e-mail")) {
            txtEmail.setText("");
        }
    }//GEN-LAST:event_txtEmailFocusGained
    /*FocusLost, Quando o componente perde o foco (deixa de ser selecionado).*/
    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // Verifica se o texto atual do campo de texto (txtEmail) está vazio.
        if (txtEmail.getText().equals("")) {
            txtEmail.setText("Digite seu e-mail");
            // Se estiver vazio, o texto é definido como "Digite seu e-mail".
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        String email = txtEmail.getText();
        String senha = new String(senhaPasswordField.getPassword());
        emailLogin = email;

        try {
            Login login = new Login(email, senha){};
            LoginDAO logindao = new LoginDAO();
            Funcionario funcionario = new Funcionario(email,senha);
            FuncionarioDAO funcionariodao = new FuncionarioDAO();
            if (logindao.existe(login)) {
                DashboardPrincipal GoToDash = new DashboardPrincipal();
                GoToDash.setVisible(true);
                this.dispose();
            } else if(funcionariodao.existe(funcionario)){
                DashboardAdmin GoToAdminDash = new DashboardAdmin();
                GoToAdminDash.setVisible(true);
                this.dispose();
            } 
            else {
                JOptionPane.showMessageDialog(null, "E-mail ou senha incorretos. \n Verifique suas informações e tente novamente.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problemas técnicos. Tente novamente mais tarde");
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private images.SVGImage BackgroundLeft;
    private images.SVGImage BackgroundRight;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblRegistre;
    private javax.swing.JPasswordField senhaPasswordField;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables

}
