package view;

import javax.swing.*;
import view.SelectedCadastroPaciente.InsertTelefonePaciente;
import view.SelectedCadastroProfissional.InsertPersonalDataProfissional;

public class ViewSelectTypeCadastro extends javax.swing.JFrame {

    /**
     * Creates new form SelectType
     */
    public ViewSelectTypeCadastro() {
        initComponents();
        /*Icon Janela*/
        // Define o ícone da janela como a imagem localizada em "/images/icon.png".
        setIconImage(new ImageIcon(getClass().getResource("/images/icon.png")).getImage());
        // Define a posição da janela como centralizada em relação à tela.
        this.setLocationRelativeTo(null);
        // Define a imagem de fundo SVG
        BackgroundRight.setSvgImage("images/BackgroundRight.svg", 618, 640);
        // Imagem botão de retorno
        btnReturn.setSvgImage("images/returnIcon.svg", 44, 35);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelectTypeCadastroFrame = new javax.swing.JPanel();
        btnSouPaciente = new javax.swing.JButton();
        btnSouProfissional = new javax.swing.JButton();
        BackgroundRight = new images.SVGImage();
        jLabel1 = new javax.swing.JLabel();
        btnReturn = new images.SVGImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tipo de Cadastro");
        setMaximumSize(new java.awt.Dimension(1000, 640));
        setResizable(false);

        SelectTypeCadastroFrame.setBackground(new java.awt.Color(255, 255, 255));
        SelectTypeCadastroFrame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSouPaciente.setBackground(new java.awt.Color(227, 1, 64));
        btnSouPaciente.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSouPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnSouPaciente.setText("Paciente");
        btnSouPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSouPacienteActionPerformed(evt);
            }
        });
        SelectTypeCadastroFrame.add(btnSouPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 308, 210, 35));

        btnSouProfissional.setBackground(new java.awt.Color(227, 1, 64));
        btnSouProfissional.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSouProfissional.setForeground(new java.awt.Color(255, 255, 255));
        btnSouProfissional.setText("Profissional");
        btnSouProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSouProfissionalActionPerformed(evt);
            }
        });
        SelectTypeCadastroFrame.add(btnSouProfissional, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 353, 210, 35));
        SelectTypeCadastroFrame.add(BackgroundRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 618, 640));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel1.setText("O que você é?");
        SelectTypeCadastroFrame.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        btnReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReturnMouseClicked(evt);
            }
        });
        SelectTypeCadastroFrame.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 44, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SelectTypeCadastroFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SelectTypeCadastroFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSouPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSouPacienteActionPerformed
        // Cria uma instância da classe ViewSelectedPaciente
        InsertTelefonePaciente openSelectedPaciente = new InsertTelefonePaciente();
        // Torna a janela atual invisível
        this.setVisible(false);
        // Torna a janela openSelectedPaciente visível
        openSelectedPaciente.setVisible(true);
    }//GEN-LAST:event_btnSouPacienteActionPerformed

    private void btnSouProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSouProfissionalActionPerformed
        // Cria uma instância da classe ViewSelectedProfissional
        InsertPersonalDataProfissional openSelectedProfissional = new InsertPersonalDataProfissional();
        // Torna a janela atual invisível
        this.setVisible(false);
        // Torna a janela openSelectedProfissional visível
        openSelectedProfissional.setVisible(true);
    }//GEN-LAST:event_btnSouProfissionalActionPerformed
    /*Ação do botão voltar*/
    private void btnReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReturnMouseClicked
        ViewLogin returnToLogin = new ViewLogin();
        returnToLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReturnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSelectTypeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSelectTypeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSelectTypeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSelectTypeCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSelectTypeCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private images.SVGImage BackgroundRight;
    private javax.swing.JPanel SelectTypeCadastroFrame;
    private images.SVGImage btnReturn;
    private javax.swing.JButton btnSouPaciente;
    private javax.swing.JButton btnSouProfissional;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
