package view.Dashboard;

import database.ConexaoBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class DashboardPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public DashboardPrincipal() {
        initComponents();
        Table1.setVisible(false);
        Table2.setVisible(false);
        backgroundtable.setVisible(false);
        /*Icon Janela*/
        // Define o ícone da janela como a imagem localizada em "/images/icon.png".
        setIconImage(new ImageIcon(getClass().getResource("/images/icon.png")).getImage());
        // Define a posição da janela como centralizada em relação à tela.
        this.setLocationRelativeTo(null);
        // Imagens
        backgroundHomeScreen.setSvgImage("Images/Dashboard/HomeImage.svg", 709, 520);
        btnMeuPerfil.setSvgImage("images/Dashboard/meuperfil.svg", 115, 23);
        btnInicio.setSvgImage("images/Dashboard/inicioicon.svg", 76, 22);
        btnPsicologo.setSvgImage("images/Dashboard/psicologoicon.svg", 119, 23);
        btnPsiquiatra.setSvgImage("images/Dashboard/psiquiatraicon.svg", 121, 23);
        btnSair.setSvgImage("images/Dashboard/btnSair.svg", 64, 32);
        backgroundtable.setSvgImage("images/Dashboard/backgroundtabela.svg", 1235, 640);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        backgroundHomeScreen = new images.SVGImage();
        btnMeuPerfil = new images.SVGImage();
        btnInicio = new images.SVGImage();
        btnPsicologo = new images.SVGImage();
        btnPsiquiatra = new images.SVGImage();
        btnSair = new images.SVGImage();
        Table1 = new javax.swing.JScrollPane();
        tablePsicologo = new javax.swing.JTable();
        Table2 = new javax.swing.JScrollPane();
        tablePsiquiatra = new javax.swing.JTable();
        backgroundtable = new images.SVGImage();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard - Mente Livre Brasil");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundHomeScreen.setText("imagehome");
        jPanel1.add(backgroundHomeScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 709, 520));

        btnMeuPerfil.setText("meuperfilicon");
        btnMeuPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMeuPerfilMouseClicked(evt);
            }
        });
        jPanel1.add(btnMeuPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 29, 115, 23));

        btnInicio.setText("inicio");
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });
        jPanel1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 29, 76, 22));

        btnPsicologo.setText("psicologo");
        btnPsicologo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPsicologoMouseClicked(evt);
            }
        });
        jPanel1.add(btnPsicologo, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 29, 119, 23));

        btnPsiquiatra.setText("psiquiatra");
        btnPsiquiatra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPsiquiatraMouseClicked(evt);
            }
        });
        jPanel1.add(btnPsiquiatra, new org.netbeans.lib.awtextra.AbsoluteConstraints(687, 29, 121, 23));

        btnSair.setText("sair");
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        jPanel1.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 675, 64, 32));

        Table1.setBorder(null);

        tablePsicologo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tablePsicologo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Profissionalização", "Tipo de Atendimento", "Telefone", "Endereço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePsicologo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablePsicologo.setRowHeight(35);
        tablePsicologo.setSelectionBackground(new java.awt.Color(227, 1, 64));
        Table1.setViewportView(tablePsicologo);
        if (tablePsicologo.getColumnModel().getColumnCount() > 0) {
            tablePsicologo.getColumnModel().getColumn(1).setPreferredWidth(250);
            tablePsicologo.getColumnModel().getColumn(1).setMaxWidth(250);
            tablePsicologo.getColumnModel().getColumn(2).setPreferredWidth(120);
            tablePsicologo.getColumnModel().getColumn(2).setMaxWidth(120);
            tablePsicologo.getColumnModel().getColumn(3).setPreferredWidth(140);
            tablePsicologo.getColumnModel().getColumn(3).setMaxWidth(140);
            tablePsicologo.getColumnModel().getColumn(4).setResizable(false);
            tablePsicologo.getColumnModel().getColumn(4).setPreferredWidth(35);
        }

        jPanel1.add(Table1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 80, 1235, 630));

        Table2.setBorder(null);

        tablePsiquiatra.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tablePsiquiatra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Profissionalização", "Tipo de Atendimento", "Telefone", "Endereço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePsiquiatra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablePsiquiatra.setRowHeight(35);
        tablePsiquiatra.setSelectionBackground(new java.awt.Color(227, 1, 64));
        Table2.setViewportView(tablePsiquiatra);
        if (tablePsiquiatra.getColumnModel().getColumnCount() > 0) {
            tablePsiquiatra.getColumnModel().getColumn(0).setResizable(false);
            tablePsiquiatra.getColumnModel().getColumn(1).setPreferredWidth(250);
            tablePsiquiatra.getColumnModel().getColumn(1).setMaxWidth(250);
            tablePsiquiatra.getColumnModel().getColumn(2).setPreferredWidth(120);
            tablePsiquiatra.getColumnModel().getColumn(2).setMaxWidth(120);
            tablePsiquiatra.getColumnModel().getColumn(3).setPreferredWidth(140);
            tablePsiquiatra.getColumnModel().getColumn(3).setMaxWidth(140);
            tablePsiquiatra.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(Table2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 80, 1235, 630));

        backgroundtable.setText("backgroundtabela");
        jPanel1.add(backgroundtable, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 80, 1235, 640));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPsiquiatraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPsiquiatraMouseClicked
        backgroundHomeScreen.setVisible(false);
        backgroundtable.setVisible(true);
        try {
            consultarPsiquiatra();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível buscar os dados do banco.");
        }
        Table1.setVisible(false);
        Table2.setVisible(true);
    }//GEN-LAST:event_btnPsiquiatraMouseClicked

    private void btnPsicologoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPsicologoMouseClicked
        backgroundHomeScreen.setVisible(false);
        backgroundtable.setVisible(true);
        try {
            consultarPsicologo();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível buscar os dados do banco.");
        }
        Table1.setVisible(true);
        Table2.setVisible(false);
    }//GEN-LAST:event_btnPsicologoMouseClicked

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        backgroundHomeScreen.setVisible(true);
        backgroundtable.setVisible(false);
        Table1.setVisible(false);
        Table2.setVisible(false);
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnMeuPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMeuPerfilMouseClicked
        DashboardMeuPerfil GoToMeuPerfil = new DashboardMeuPerfil();
        GoToMeuPerfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMeuPerfilMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSairMouseClicked
    // CONSTRUTOR TABELA PSIQUIATRA
    public void consultarPsiquiatra() throws Exception {
        DefaultTableModel model = (DefaultTableModel) tablePsiquiatra.getModel();
        model.setRowCount(0);

        String sql = """
                     SELECT nome, profissionalizacao, tipo_consulta, telefone_psiquiatra.comercial, CONCAT(endereco_psiquiatra.rua, ', ', endereco_psiquiatra.bairro, ', ', endereco_psiquiatra.estado) AS endereco_completo
                     FROM psiquiatra
                     INNER JOIN telefone_psiquiatra ON psiquiatra.cod_tel = telefone_psiquiatra.cod_tel
                     INNER JOIN endereco_psiquiatra ON psiquiatra.cod_endereco = endereco_psiquiatra.cod_endereco;""";
        try (Connection conn = ConexaoBD.obtemConexao(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getLong(4), rs.getString(5)});
            }
        }
    }

    // CONSTRUTOR TABELA PSICOLOGO
    public void consultarPsicologo() throws Exception {
        DefaultTableModel model = (DefaultTableModel) tablePsicologo.getModel();
        model.setRowCount(0);

        String sql = """
                     SELECT nome, profissionalizacao, tipo_consulta, telefone_psicologo.comercial, CONCAT(endereco_psicologo.rua, ', ', endereco_psicologo.bairro, ', ', endereco_psicologo.estado) AS endereco_completo
                     FROM psicologo
                     INNER JOIN telefone_psicologo ON psicologo.cod_tel = telefone_psicologo.cod_tel
                     INNER JOIN endereco_psicologo ON psicologo.cod_endereco = endereco_psicologo.cod_endereco;""";
        try (Connection conn = ConexaoBD.obtemConexao(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getLong(4), rs.getString(5)});
            }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Table1;
    private javax.swing.JScrollPane Table2;
    private images.SVGImage backgroundHomeScreen;
    private images.SVGImage backgroundtable;
    private images.SVGImage btnInicio;
    private images.SVGImage btnMeuPerfil;
    private images.SVGImage btnPsicologo;
    private images.SVGImage btnPsiquiatra;
    private images.SVGImage btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablePsicologo;
    private javax.swing.JTable tablePsiquiatra;
    // End of variables declaration//GEN-END:variables
}
